name: mm-predict
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - xgboost
  - lightgbm
  - optuna
  - shap
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  - ipykernel
  - pyarrow
  - beautifulsoup4
  - lxml
  - rapidfuzz
  - pip
